In [1]:
from neuromatch.read import read_all_to_all_indexes, read_all_to_all_psame
import time
import sys
from neuromatch.variables import AllToAll, IndexMap
from neuromatch.read import read_index_map


a = read_all_to_all_indexes(r"E:\Data\Cross_maze\10227\Super Long-term Maze 1\Cell_reg\modeled_data_struct.mat")
b = AllToAll(a)
b[0, 1, 1]

In [3]:
from neuromatch.read import read_all_to_all_indexes, read_all_to_all_psame
import time
import sys
import numpy as np
from neuromatch.variables import AllToAll, IndexMap
from neuromatch.read import read_index_map


c = read_index_map(r"E:\Data\Cross_maze\10227\Super Long-term Maze 1\Cell_reg\cellRegistered.mat")
d = IndexMap(c)
print(d)
print(d[0, 0])
d.sort()
print(d)
print(d.count_nonzero().shape)
print(d.add_col(np.random.randint(1, 4, size=[26,1])))
print(d.remove_col(-1))


[[  1   2   3 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [151   0 122 ...   0   0   0]
 ...
 [  0 104 175 ...   0   0   0]
 [  0 130   0 ...   0   0   0]
 [  0  89 182 ... 589 590   0]]
1
[[295 166 256 ...   0   0   0]
 [210 285 401 ... 597   0   0]
 [196 602  76 ...   0   0   0]
 ...
 [390 452 210 ...   0   0   0]
 [370 306 102 ...   0   0   0]
 [322 241  97 ...   0   0   0]]
(2588,)
[[295 166 256 ...   0   0   2]
 [210 285 401 ...   0   0   2]
 [196 602  76 ...   0   0   1]
 ...
 [390 452 210 ...   0   0   2]
 [370 306 102 ...   0   0   3]
 [322 241  97 ...   0   0   3]]
[[295 166 256 ...   0   0   0]
 [210 285 401 ... 597   0   0]
 [196 602  76 ...   0   0   0]
 ...
 [390 452 210 ...   0   0   0]
 [370 306 102 ...   0   0   0]
 [322 241  97 ...   0   0   0]]
[[295 166 256 ...   0   0   0]
 [210 285 401 ... 597   0   0]
 [196 602  76 ...   0   0   0]
 ...
 [370 306 102 ...   0   0   0]
 [322 241  97 ...   0   0   0]
 [  2   3   1 ...   1   1   3]]
[[295 166 256 ...   0   0   0]